version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: operary-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: operary-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=operary_dev
      - ORG_TOKEN=demo-org-token

  ui:
    build:
      context: ./ui
    container_name: operary-ui
    ports:
      - "3000:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: operary-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana-oss
    container_name: operary-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  mongo-data:
