
version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: operary-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
    container_name: operary-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=operary_dev
      - ORG_TOKEN=demo-org-token

volumes:
  mongo-data:
